on: [push]

jobs:
  sbom:
    runs-on: ubuntu-latest
    name: SPDX SBOM Generator
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: NPM install
        run: npm install
      - name: Generate SBOM
        uses: spacedog/gh-action-spdx-sbom-generator@main
        with:
          arch: 386
          version: 0.0.15
      - name: Output SBOM reports
        run: cat *.spdx >> $GITHUB_OUTPUT
